import { 
  ImageIcon, 
  FileText, 
  Type, 
  Code, 
  Calculator, 
  Zap, 
  Search, 
  Ruler, 
  MoreHorizontal,
  FilePlus,
  Scissors,
  RotateCw,
  Layers,
  Split,
  FileImage,
  FileArchive,
  Hash,
  CaseSensitive,
  AlignLeft,
  SortAsc,
  Copy,
  Braces,
  Settings,
  Globe,
  FileJson,
  Calendar,
  Percent,
  CreditCard,
  Coins,
  Lock,
  QrCode,
  Fingerprint,
  Dices,
  Tag,
  BarChart,
  Link,
  Scale,
  Thermometer,
  Clock,
  Volume2,
  Mic,
  Palette,
  Timer
} from "lucide-react";
import { CategoryInfo } from "../types/tool";

export const CATEGORIES: CategoryInfo[] = [
  { id: "image", name: "Image Tools", icon: ImageIcon, color: "bg-pink-100 text-pink-600" },
  { id: "pdf", name: "PDF Tools", icon: FileText, color: "bg-indigo-100 text-indigo-600" },
  { id: "text", name: "Text Tools", icon: Type, color: "bg-blue-100 text-blue-600" },
  { id: "developer", name: "Developer Tools", icon: Code, color: "bg-slate-100 text-slate-600" },
  { id: "calculator", name: "Calculators", icon: Calculator, color: "bg-emerald-100 text-emerald-600" },
  { id: "generator", name: "Generators", icon: Zap, color: "bg-amber-100 text-amber-600" },
  { id: "seo", name: "SEO Tools", icon: Search, color: "bg-violet-100 text-violet-600" },
  { id: "unit", name: "Unit Converters", icon: Ruler, color: "bg-cyan-100 text-cyan-600" },
  { id: "misc", name: "Misc Tools", icon: MoreHorizontal, color: "bg-rose-100 text-rose-600" },
];
